REM Build Bat File
REM Precheck the Resource 
"C:\Program Files (x86)\MRE SDK V3.0.00\tools\ResEditor\CmdShell.exe" save  "I:\BadVXP\BadVXP_MRE3.0\BadVXP.vcproj"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery G++ Lite\Bin\arm-none-eabi-gcc" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "I:\BadVXP\BadVXP_MRE3.0\arm\gccmain.o" -c "C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE30\src\gccmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files (x86)\MRE SDK V3.0.00\include" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include\service" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include\service" -I "I:\BadVXP\BadVXP_MRE3.0\include" -I "I:\BadVXP\BadVXP_MRE3.0\include\service" -I "I:\BadVXP\BadVXP_MRE3.0\include\component" -I "I:\BadVXP\BadVXP_MRE3.0\ResID" -I "I:\BadVXP\BadVXP_MRE3.0\src\app\widget" -I "I:\BadVXP\BadVXP_MRE3.0\src\app\launcher" -I "I:\BadVXP\BadVXP_MRE3.0\src\app\wallpaper" -I "I:\BadVXP\BadVXP_MRE3.0\src\app\screen_lock" -I "I:\BadVXP\BadVXP_MRE3.0\include\service" -I "I:\BadVXP\BadVXP_MRE3.0\include\component" -I "I:\BadVXP\BadVXP_MRE3.0\include\service" -I "I:\BadVXP\BadVXP_MRE3.0\src\framework" -I "I:\BadVXP\BadVXP_MRE3.0\src\framework\ui_core\base" -I "I:\BadVXP\BadVXP_MRE3.0\src\framework\ui_core\mvc" -I "I:\BadVXP\BadVXP_MRE3.0\src\framework\ui_core\pme" -I "I:\BadVXP\BadVXP_MRE3.0\src\framework\mmi_core" -I "I:\BadVXP\BadVXP_MRE3.0\src\ui_engine\vrt\interface" -I "I:\BadVXP\BadVXP_MRE3.0\src\component" -I "I:\BadVXP\BadVXP_MRE3.0\src\ui_engine\framework\xml" -I "I:\BadVXP\BadVXP_MRE3.0"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery G++ Lite\Bin\arm-none-eabi-gcc" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "I:\BadVXP\BadVXP_MRE3.0\arm\BadVXP.o" -c "i:\BadVXP\BadVXP_MRE3.0\BadVXP.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files (x86)\MRE SDK V3.0.00\include" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include\service" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include\service" -I "I:\BadVXP\BadVXP_MRE3.0\include" -I "I:\BadVXP\BadVXP_MRE3.0\include\service" -I "I:\BadVXP\BadVXP_MRE3.0\include\component" -I "I:\BadVXP\BadVXP_MRE3.0\ResID" -I "I:\BadVXP\BadVXP_MRE3.0\src\app\widget" -I "I:\BadVXP\BadVXP_MRE3.0\src\app\launcher" -I "I:\BadVXP\BadVXP_MRE3.0\src\app\wallpaper" -I "I:\BadVXP\BadVXP_MRE3.0\src\app\screen_lock" -I "I:\BadVXP\BadVXP_MRE3.0\include\service" -I "I:\BadVXP\BadVXP_MRE3.0\include\component" -I "I:\BadVXP\BadVXP_MRE3.0\include\service" -I "I:\BadVXP\BadVXP_MRE3.0\src\framework" -I "I:\BadVXP\BadVXP_MRE3.0\src\framework\ui_core\base" -I "I:\BadVXP\BadVXP_MRE3.0\src\framework\ui_core\mvc" -I "I:\BadVXP\BadVXP_MRE3.0\src\framework\ui_core\pme" -I "I:\BadVXP\BadVXP_MRE3.0\src\framework\mmi_core" -I "I:\BadVXP\BadVXP_MRE3.0\src\ui_engine\vrt\interface" -I "I:\BadVXP\BadVXP_MRE3.0\src\component" -I "I:\BadVXP\BadVXP_MRE3.0\src\ui_engine\framework\xml" -I "I:\BadVXP\BadVXP_MRE3.0"
REM Link app 
"C:\Program Files (x86)\CodeSourcery\Sourcery G++ Lite\Bin\arm-none-eabi-gcc" -o "I:\BadVXP\BadVXP_MRE3.0\BadVXP.axf"  "I:\BadVXP\BadVXP_MRE3.0\arm\gccmain.o"  "I:\BadVXP\BadVXP_MRE3.0\arm\BadVXP.o" -fpic -msvr4-struct-return -pie  -T "C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE30\armgcc\scat.ld" -l:"C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE30\armgcc\percommon.a" -l:"C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE30\armgcc\pertcp.a" -l:"C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE30\armgcc\persensor.a" -l:"C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE30\armgcc\persmsper.a" -l:"C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE30\armgcc\perbitstream.a" -l:"C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE30\armgcc\percontact.a" -l:"C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE30\armgcc\permms.a" -l:"C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE30\armgcc\persmsmng.a"
REM Pack resource to app 
"C:\Program Files (x86)\MRE SDK V3.0.00\tools\ResEditor\CmdShell.exe" pack -silent -resolution 240x320 -o "I:\BadVXP\BadVXP_MRE3.0\BadVXP.pkd" -e AXF "I:\BadVXP\BadVXP_MRE3.0\BadVXP.vcproj" "I:\BadVXP\BadVXP_MRE3.0\BadVXP.axf"
REM Add tag infromation 
"C:\Program Files (x86)\MRE SDK V3.0.00\tools\PackDigist.exe" "I:\BadVXP\BadVXP_MRE3.0\BadVXP.vcproj" "BadAppleVXP_3.0" "0.1.0" "Raul0028" "500" "NotSupportBg" "Not Support rotate" "BadAppleVXP_3.0" "BadAppleVXP_3.0" "BadAppleVXP_3.0" "1234567890" "content" " TCP Sensor SMS(person) BitStream Contact MMS SMSMng" "vxp" "GCC" "PKD" "UnCompress" "NoVPI" "UnAdaptable" "15728960" "UnSysMemAble" "
    " "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  I:\BadVXP\BadVXP_MRE3.0\arm I:\BadVXP\BadVXP_MRE3.0\build.log

