REM Build Bat File
REM Precheck the Resource 
"C:\Program Files (x86)\MRE SDK V3.0.00\tools\ResEditor\CmdShell.exe" save  "I:\BadVXP\BadVXP\BadVXP.vcproj"
REM Copmile c file 
"C:\Program Files\ARM\RVCT\Programs\3.1\569\win_32-pentium\armcc" -O3 -g --no_inline --split_sections --apcs=/fpic -cpu ARM7EJ-S -D__MRE_COMPILER_RVCT__ -o "I:\BadVXP\BadVXP\arm\rvctmain.o" -c "C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE20\src\rvctmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files (x86)\MRE SDK V3.0.00\include" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include\service" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include\service" -I "I:\BadVXP\BadVXP\include" -I "I:\BadVXP\BadVXP\include\service" -I "I:\BadVXP\BadVXP\include\component" -I "I:\BadVXP\BadVXP\ResID" -I "I:\BadVXP\BadVXP\src\app\widget" -I "I:\BadVXP\BadVXP\src\app\launcher" -I "I:\BadVXP\BadVXP\src\app\wallpaper" -I "I:\BadVXP\BadVXP\src\app\screen_lock" -I "I:\BadVXP\BadVXP\include\service" -I "I:\BadVXP\BadVXP\include\component" -I "I:\BadVXP\BadVXP\include\service" -I "I:\BadVXP\BadVXP\src\framework" -I "I:\BadVXP\BadVXP\src\framework\ui_core\base" -I "I:\BadVXP\BadVXP\src\framework\ui_core\mvc" -I "I:\BadVXP\BadVXP\src\framework\ui_core\pme" -I "I:\BadVXP\BadVXP\src\framework\mmi_core" -I "I:\BadVXP\BadVXP\src\ui_engine\vrt\interface" -I "I:\BadVXP\BadVXP\src\component" -I "I:\BadVXP\BadVXP\src\ui_engine\framework\xml" -I "I:\BadVXP\BadVXP" --errors "I:\BadVXP\BadVXP\BadVXP.log"
REM Copmile c file 
"C:\Program Files\ARM\RVCT\Programs\3.1\569\win_32-pentium\armcc" -O3 -g --no_inline --split_sections --apcs=/fpic -cpu ARM7EJ-S -D__MRE_COMPILER_RVCT__ -o "I:\BadVXP\BadVXP\arm\BadVXP.o" -c "i:\BadVXP\BadVXP\BadVXP.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files (x86)\MRE SDK V3.0.00\include" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include\service" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include\service" -I "I:\BadVXP\BadVXP\include" -I "I:\BadVXP\BadVXP\include\service" -I "I:\BadVXP\BadVXP\include\component" -I "I:\BadVXP\BadVXP\ResID" -I "I:\BadVXP\BadVXP\src\app\widget" -I "I:\BadVXP\BadVXP\src\app\launcher" -I "I:\BadVXP\BadVXP\src\app\wallpaper" -I "I:\BadVXP\BadVXP\src\app\screen_lock" -I "I:\BadVXP\BadVXP\include\service" -I "I:\BadVXP\BadVXP\include\component" -I "I:\BadVXP\BadVXP\include\service" -I "I:\BadVXP\BadVXP\src\framework" -I "I:\BadVXP\BadVXP\src\framework\ui_core\base" -I "I:\BadVXP\BadVXP\src\framework\ui_core\mvc" -I "I:\BadVXP\BadVXP\src\framework\ui_core\pme" -I "I:\BadVXP\BadVXP\src\framework\mmi_core" -I "I:\BadVXP\BadVXP\src\ui_engine\vrt\interface" -I "I:\BadVXP\BadVXP\src\component" -I "I:\BadVXP\BadVXP\src\ui_engine\framework\xml" -I "I:\BadVXP\BadVXP" --errors "I:\BadVXP\BadVXP\BadVXP.log"
REM Link app 
"C:\Program Files\ARM\RVCT\Programs\3.1\569\win_32-pentium\armlink" -o "I:\BadVXP\BadVXP\BadVXP.axf"  "I:\BadVXP\BadVXP\arm\rvctmain.o"  "I:\BadVXP\BadVXP\arm\BadVXP.o" --fpic --sysv --entry rvct_entry --first rvct_entry "C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE20\armrvct\percommon.a" "C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE20\armrvct\perbitstream.a" "C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE20\armrvct\perfile.a" --errors "I:\BadVXP\BadVXP\BadVXP.log"
REM Pack resource to app 
"C:\Program Files (x86)\MRE SDK V3.0.00\tools\ResEditor\CmdShell.exe" pack -silent -resolution 240x320 -o "I:\BadVXP\BadVXP\BadVXP.pkd" -e AXF "I:\BadVXP\BadVXP\BadVXP.vcproj" "I:\BadVXP\BadVXP\BadVXP.axf"
REM Add tag infromation 
"C:\Program Files (x86)\MRE SDK V3.0.00\tools\PackDigist.exe" "I:\BadVXP\BadVXP\BadVXP.vcproj" "BadAppleVXP" "0.1.0" "Raul0028" "500" "NotSupportBg" "Not Support rotate" "BadAppleVXP" "BadAppleVXP" "BadAppleVXP" "1234567890" "content" " BitStream File" "vxp" "RVCT" "PKD" "UnCompress" "NoVPI" "UnAdaptable" "15728960" "UnSysMemAble" "
    " "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  I:\BadVXP\BadVXP\arm I:\BadVXP\BadVXP\build.log

